In [47]:
import pandas as pd
import matplotlib.pyplot as plt

inladen data:

In [48]:
df = pd.read_csv('heart_2020_cleaned.csv')
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

overview data:

In [51]:
df.describe(include='all')

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
count,319795,319795.000000,319795,319795,319795,319795.00000,319795.000000,319795,319795,319795,319795,319795,319795,319795,319795.000000,319795,319795,319795
unique,2,NaN,2,2,2,NaN,NaN,2,2,13,6,4,2,5,NaN,2,2,2
top,No,NaN,No,No,No,NaN,NaN,No,Female,65-69,White,No,Yes,Very good,NaN,No,No,No
freq,292422,NaN,187887,298018,307726,NaN,NaN,275385,167805,34151,245212,269653,247957,113858,NaN,276923,308016,289976
mean,NaN,28.325399,NaN,NaN,NaN,3.37171,3.898366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.097075,NaN,NaN,NaN
std,NaN,6.356100,NaN,NaN,NaN,7.95085,7.955235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.436007,NaN,NaN,NaN
min,NaN,12.020000,NaN,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,NaN,24.030000,NaN,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN
50%,NaN,27.340000,NaN,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,NaN
75%,NaN,31.420000,NaN,NaN,NaN,2.00000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN
max,NaN,94.850000,NaN,NaN,NaN,30.00000,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.000000,NaN,NaN,NaN

In [54]:
df.dtypes

HeartDisease         object
BMI                 float64
Smoking              object
AlcoholDrinking      object
Stroke               object
PhysicalHealth      float64
MentalHealth        float64
DiffWalking          object
Sex                  object
AgeCategory          object
Race                 object
Diabetic             object
PhysicalActivity     object
GenHealth            object
SleepTime           float64
Asthma               object
KidneyDisease        object
SkinCancer           object
dtype: object

Wat blijkt uit de overview is dat veel datapunten niet normaal verdeeld zijn.
Heart disease is niet gebalanceerd, ongeveer 85 heeft geen heart disease.
De BMI ligt hoog, het ligt gemiddeld op 27 dus veel mensen uit dit onderzoek hebben overgewicht.
AlcoholDrinking is niet gebalanceerd 94% van de mensen uit dit onderzoek drinkt geen alcohol.
Stroke is niet gebalanceerd 96% van de mensen uit dit onderzoek heeft geen beroerte gehad.
PhysicalHealth en MentalHealth zijn niet representatief omdat bij het overgrote deel van de mensen 0 is ingevuld.
Diffwalking is niet gebalanceerd 86% van de mensen heeft geen moeite met lopen
Sex is redelijk gebalanceerd 52% van de mensen is vrouw.
AgeCategory is verdeeld in categoriën waarvan 65-69 het meest voorkomt.
Race is niet gebalanceerd 76% van de mensen iis blank.
Diabetic is niet gebalanceerd 84% van de mensen heeft geen diabetes.
PhysicalActivity is niet gebalanceerd 77% van de mensen is actief.
GenHealth is verdeelt in groepen de grootste groep is mensen met een hele goede gezondheid.
SleepTime is normaal verdeeld het gemiddelde aantal uren dat mensen per dag slapen is 7,1.
Asthma is niet gebalanceerd 86% van de mensen heeft geen asthma
KidneyDisease is niet gebalanceerd 96% van de mensen heeft geen nier ziektes.
SkinCancer is niet gebalanceerd 91% van de mensen heeft geen huid kanker.

In [55]:
df.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

deze data bevat geen NaN